### ISSUE TITLE
[BUG] Invalid pattern with relative path in .gitignore

### ISSUE THREAD

**Issue by chicocvenancio** [tj-actions/glob#445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

With the latest release we get 
```
Invalid pattern */./*.yaml'. Relative pathing '.' and '..' is not allowed.
```
Since our .gitignore has `./*.yaml`.

### To Reproduce

1. Place `./*.yaml` in .gitignore
2. Try to use the action

### What OS are you seeing the problem on?

all

### Expected behavior?

No errors.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@chicocvenancio @thealgirdas @arthurk This has now been resolved in the latest release.
